main: me.goodgamer123.SimbaCore.MainClass
name:  SimbaCore
version: 1.0.0
api-version: 1.8
author: goodgamer123
description: SimbaCore.

commands:
  op:
    description: op players.
  screenshare:
    description: screen share.
    permission: screenshare.screenshare
    aliases: [ss]