main: me.goodgamer123.SimbaFactions.MainClass
name:  SimbaFactions
version: 1.0.0
api-version: 1.8
author: goodgamer123
description: SimbaFactions.

commands:
  gradi:
    description: gradi.
    permission: gradi.gradi