main: me.goodgamer123.SimbaKitPVP.MainClass
name:  SimbaKitPVP
version: 1.2.0
api-version: 1.8
author: goodgamer123
description: SimbaKitPVP.

commands:
  gradi:
    description: gradi.
    permission: gradi.gradi