main: me.goodgamer123.SimbaMainHub.MainClass
name:  SimbaMainHub
version: 1.0.0
api-version: 1.8
author: goodgamer123
description: Shows particles on join.

commands:
  gradi:
    description: Gradi.
    permission: gradi.gradi
  ipwhitelist:
    description: Ip whitelist.
    permission: ipwhitelist.ipwhitelist
  togglespeed:
    description: Toggle your speed.
  toggleplayers:
    description: Toggle your players.
  togglesounds:
    description: Toggle your sounds.
  togglekb:
    description: Toggle your knockback.
  toggledj:
    description: Toggle your double jump.